"""add upi fields

Revision ID: f6938e96b5c7
Revises: 3721816bbb34
Create Date: 2026-04-27 02:27:15.491933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6938e96b5c7'
down_revision = '3721816bbb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('utr_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('upi_qr_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('upi_qr_image')
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('utr_number')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
